### ISSUE TITLE
Same url_title doesn't return correct entry_id

### ISSUE THREAD

**Issue by mkinberg** [nathanpitman/url_title_to_entry_id.pi.ee_addon#2]
I have two url_titles that have the same name (a product name).  One resides in a "Pre-Owned" channel and the other in a "Parts & Accessories" channel.

When I use url_title_to_entry, it will only pull in the ID of the Pre-Owned channel (ID#8 instead of ID#29).  My exp:channel:entries tag has the channel specified, so it should be pulling in the correct url_title.

To get around this, I've renamed the url_title for each entry in the Parts & Accessories channel.  However there's fear that my client will name the url_title the same in each type of entry.

Thanks

**Comment by gmhenderson** [comment]
This is old, but I just submitted a pull request to accommodate your issue. d2db44bc171d7d4395c40527fdf23af6ba81637e

**Comment by nathanpitman** [comment]
I'm a bit confused by this as I thought EE prevented identical url_titles... am I missing something? :)

**Comment by nathanpitman** [comment]
Also, sorry for the very late reply... I had my GitHub notification settings messed up.

**Comment by gmhenderson** [comment]
You can have duplicate url_titles in different channels, see the note [here](https://ellislab.com/expressionengine/user-guide/add-ons/channel/channel_entries.html#url-title).

**Comment by nathanpitman** [comment]
Never knew that... in which case merge I will! Thanks @gmhenderson :)

**Comment by nathanpitman** [comment]
LOL, I'm in such a muddle. I merged it already least year. Must be getting old.
