### ISSUE TITLE
General Usage

### ISSUE THREAD

**Issue by KevinOrfas** [nathanpitman/url_title_to_entry_id.pi.ee_addon#4]
I am trying to use your plugin but I have come across couple of issues.
First, after placing the plugin into the plugin and third_party folders, the plugin is not visible on the backend. 

Second where do I place this {exp:url_title_to_entry_id url_title="{segment_2}" channel="channel_short_name”};

**Comment by nathanpitman** [comment]
Hmm, I think it's possible I have the folder structure here incorrectly represented... the plug-in should reside at: /system/third_party/, NOT /system/plugins/ as suggested.

You should place the tag for the plug-in anywhere within your template where you wish to output the entry_id of the current page. So if your page url was:

```
http://www.example.com/books/the_answer_to_life_the_universe_and_everything
```

and that represented an entry entry called "The answer to life, the universe and everything" which had an ID of 42 then in your template:

```
<p>{exp:url_title_to_entry_id url_title="{segment_2}" channel="books"}</p>
```

would output:

```
<p>42</p>
```

Hope that helps! :)
